[package]
name = "solana-demo"
version = "0.1.0"
authors = ["@0xys"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.6.6"
solana-client = "1.6.6"